### ISSUE TITLE
Updating the User disables the user (Enabled unchecked)

### ISSUE THREAD

**Issue by stkul** [PolarbearDK/Miracle.FileZilla.Api#32]
The following code unchecked the Enabled flag for the user:

User existingUser = accountSettings.Users.Find(x => x.UserName.CompareTo(username) == 0);
existingUser.ForceSsl = TriState.Yes;
existingUser.Enabled = TriState.Yes;
existingUser.DisallowedIPs = disallowedIps;
existingUser.AllowedIPs = allowedIps;
fileZillaApi.SetAccountSettings(accountSettings);

Am I missing something?

**Comment by PolarbearDK** [comment]
Nope, looks OK to me.
Are you sure somebody else didn't modify the user?

**Comment by stkul** [comment]
Yes, this is happening every time this code is invoked. When I check the setting on the FileZilla server for the user that is just updated, the Enabled checkbox gets unchecked.

**Comment by PolarbearDK** [comment]
Sorry, forgot about this issue. 

I ran your exact code against my text FileZilla server, and everything works as expected. 
This library is quite old and battle tested and user creation is the core function. 
I think we have to look elsewhere to figure out what the problem is.

What version of FileZilla server are you using? Have you tried a different version?
What OS are you using?
